export enum EstadoCita {
  PROGRAMADA = 'PROGRAMADA',
  PENDIENTE = 'PENDIENTE',
  CONFIRMADA = 'CONFIRMADA',
  REPROGRAMADA = 'REPROGRAMADA',
  SALA_DE_ESPERA = 'SALA_DE_ESPERA',
  EN_PROCESO = 'EN_PROCESO',
  COMPLETADA = 'COMPLETADA',
  NO_ASISTIO = 'NO_ASISTIO',
  CANCELADA = 'CANCELADA',
  OTRO = 'OTRO'
}
