export enum Permission {
  // SISTEMA
  USER_READ             = 'USER_READ',
  USER_CREATE           = 'USER_CREATE',
  USER_UPDATE           = 'USER_UPDATE',
  USER_DELETE           = 'USER_DELETE',
  ROLE_MANAGE           = 'ROLE_MANAGE',

  // EMPRESA
  COMPANY_READ          = 'COMPANY_READ',
  COMPANY_CREATE        = 'COMPANY_CREATE',
  COMPANY_UPDATE        = 'COMPANY_UPDATE',
  COMPANY_MANAGE        = 'COMPANY_MANAGE',

  // EMPLEADOS
  EMPLEADO_READ         = 'EMPLEADO_READ',
  EMPLEADO_CREATE       = 'EMPLEADO_CREATE',
  EMPLEADO_UPDATE       = 'EMPLEADO_UPDATE',
  EMPLEADO_STATUS       = 'EMPLEADO_STATUS',
  EMPLEADO_DELETE       = 'EMPLEADO_DELETE',

  // HORARIOS
  HORARIO_READ          = 'HORARIO_READ',
  HORARIO_MANAGE        = 'HORARIO_MANAGE',

  // TIPOS DE EMPLEADO
  TIPO_EMPLEADO_READ    = 'TIPO_EMPLEADO_READ',
  TIPO_EMPLEADO_CREATE  = 'TIPO_EMPLEADO_CREATE',
  TIPO_EMPLEADO_UPDATE  = 'TIPO_EMPLEADO_UPDATE',
  TIPO_EMPLEADO_STATUS  = 'TIPO_EMPLEADO_STATUS',
  TIPO_EMPLEADO_DELETE  = 'TIPO_EMPLEADO_DELETE',

  // ESPECIALIDADES
  ESPECIALIDAD_READ     = 'ESPECIALIDAD_READ',
  ESPECIALIDAD_CREATE   = 'ESPECIALIDAD_CREATE',
  ESPECIALIDAD_UPDATE   = 'ESPECIALIDAD_UPDATE',
  ESPECIALIDAD_DELETE   = 'ESPECIALIDAD_DELETE',

  // CLIENTES / APODERADOS
  APODERADO_READ        = 'APODERADO_READ',
  APODERADO_CREATE      = 'APODERADO_CREATE',
  APODERADO_UPDATE      = 'APODERADO_UPDATE',
  APODERADO_STATUS      = 'APODERADO_STATUS',
  APODERADO_DELETE      = 'APODERADO_DELETE',

  // MASCOTAS
  PET_READ              = 'PET_READ',
  PET_CREATE            = 'PET_CREATE',
  PET_UPDATE            = 'PET_UPDATE',
  PET_STATUS            = 'PET_STATUS',
  PET_DELETE            = 'PET_DELETE',
  PET_WRITE             = 'PET_WRITE',
  PET_HISTORY_READ      = 'PET_HISTORY_READ',
  PET_HISTORY_WRITE     = 'PET_HISTORY_WRITE',

  // HISTORIAS CLÍNICAS
  CLINICAL_RECORD_READ   = 'CLINICAL_RECORD_READ',
  CLINICAL_RECORD_MANAGE = 'CLINICAL_RECORD_MANAGE',

  // CITAS
  CITA_READ             = 'CITA_READ',
  CITA_CREATE           = 'CITA_CREATE',
  CITA_UPDATE           = 'CITA_UPDATE',
  CITA_CANCEL           = 'CITA_CANCEL',
  CITA_INICIAR          = 'CITA_INICIAR',
  CITA_DELETE           = 'CITA_DELETE',

  // SERVICIOS
  SERVICIO_READ         = 'SERVICIO_READ',
  SERVICIO_CREATE       = 'SERVICIO_CREATE',
  SERVICIO_UPDATE       = 'SERVICIO_UPDATE',
  SERVICIO_DELETE       = 'SERVICIO_DELETE',
  SERVICIO_TOGGLE       = 'SERVICIO_TOGGLE',

  // VENTAS / PAGOS
  SALE_READ             = 'SALE_READ',
  SALE_MANAGE           = 'SALE_MANAGE',

  // ADMIN
  ADMIN_DASHBOARD       = 'ADMIN_DASHBOARD',
  EMPLEADO_DASHBOARD    = 'EMPLEADO_DASHBOARD',
  APODERADO_DASHBOARD   = 'APODERADO_DASHBOARD',
  USER_MANAGE           = 'USER_MANAGE',
}
